package org.example.s3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-03-27T23:44:37.300+08:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://www.example.org/s3/", name = "s3")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface S3 {

    @WebMethod(action = "http://www.example.org/s3/s3Operation")
    @WebResult(name = "rpl", targetNamespace = "http://www.example.org/s3/", partName = "parameters")
    public Rpl s3Operation(
        @WebParam(partName = "parameters", name = "req", targetNamespace = "http://www.example.org/s3/")
        Req parameters
    );
}
