package org.example.s4;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-03-27T23:49:06.816+08:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://www.example.org/s4/", name = "s4")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface S4 {

    @WebMethod(action = "http://www.example.org/s4/s4Operation")
    @WebResult(name = "rpl", targetNamespace = "http://www.example.org/s4/", partName = "parameters")
    public Rpl s4Operation(
        @WebParam(partName = "parameters", name = "req", targetNamespace = "http://www.example.org/s4/")
        Req parameters
    );
}
